config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#top'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post 'guest_login', to: 'sessions#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :posts, only: [:index, :new, :create, :show] do
    resources :likes, only: [:create, :destroy]
  end
  resources :my_posts, only: [:index, :show, :edit, :update, :destroy]
  resources :games do
    collection do
      get :index_list
      get :index_calendar
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string(255)      not null
#  name            :string(255)      not null
#  password_digest :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#  index_users_on_name   (name) UNIQUE
#
class User < ApplicationRecord
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)(?=.*?[\W_])[!-~]{8,}+\z/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { in: 8..20, allow_blank: true }, uniqueness: { case_sensitive: false },
                   unless: :guest?
  validates :email, length: { maximum: 255, allow_blank: true }, format: { with: VALID_EMAIL_REGEX, allow_blank: true },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8, allow_blank: true }, allow_nil: true,
                       format: { with: VALID_PASSWORD_REGEX, message: 'は英数字と記号を含めて下さい' }, unless: :guest?

  has_secure_password

  has_many :posts
  has_many :likes
  has_many :games

  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end

  def guest?
    name == 'guest_user'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :checked_guest, only: [:edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'アカウントを登録しました。'
      redirect_to posts_path
    else
      flash.now[:danger] = '登録に失敗しました。'
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を更新しました'
      redirect_to user_path(@user)
    else
      flash.now[:danger] = '更新に失敗しました。'
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = current_user
  end

  def checked_guest
    if current_user.name == 'guest_user'
      redirect_to user_path(current_user)
    end
  end
end

app/views/users/edit.html.erb
<div class='conteiner w-sm-50'>
  <div class='row justify-content-center'>
    <div class='col-xl-6 col-lg-8 shadow-sm text-main bg-sub-color-gray p-5 my-sm-5'>
      <div class='mb-5'>
        <h3 class='col-auto'><span class='display-5'>| </span>アカウント設定</h3>
      </div> 

      <%= render partial: 'shared/user_form', locals: { user: @user } %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class='conteiner w-sm-50'>
  <div class='row justify-content-center'>
    <div class='col-xl-6 col-lg-8 shadow-sm text-main bg-sub-color-gray p-5 my-sm-5'>
      <div class='mb-5'>
        <h3 class='col-auto'><span class='display-5'>| </span>アカウント登録</h3>
      </div> 

      <%= render partial: 'shared/user_form', locals: { new_user: true, user: @user } %>
      <div>
        アカウントをお持ちの方は、<%= link_to 'ログイン', login_path, class: 'link-text' %>してください。<br>
        アカウントを作成せずに利用する場合は<%= link_to 'ゲストログイン', login_path(guest_login: true), method: :post, class: 'link-text' %>をお使いください。
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='conteiner w-sm-50'>
  <div class='row justify-content-center'>
    <div class='col-xl-6 col-lg-8 shadow-sm text-main bg-sub-color-gray p-5 my-sm-5'>
      <div class='mb-5'>
        <h3 class='col-auto'><span class='display-5'>| </span>アカウント情報</h3>
      </div> 
      <div class='row mb-5'>
        <div class='col-sm-4'><%= t('activerecord.attributes.user.name') %></div>
        <div class='col-sm-8'><%= @user.name %></div>
      </div>
      <% if !(session[:guest] == 'guest_user') %>
        <div class='row mb-5'>
          <div class='col-sm-4'><%= t('activerecord.attributes.user.email') %></div>
          <div class='col-sm-8'><%= @user.email %></div>
        </div>
        <div class='row mb-5'>
          <div class='col-sm-4'><%= t('activerecord.attributes.user.password') %></div>
          <div class='col-sm-8'>xxxxxxxx</div>
        </div>
        <div class='d-grid col-12 mx-auto'>
          <%= link_to '変更する　＞', edit_user_path(@user), class: 'btn-primary-green' %>
        </div>
      <% end %>
    </div>
  </div>
</div>