config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#top'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post 'guest_login', to: 'sessions#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :posts, only: [:index, :new, :create, :show] do
    resources :likes, only: [:create, :destroy]
  end
  resources :my_posts, only: [:index, :show, :edit, :update, :destroy]
  resources :games do
    collection do
      get :index_list
      get :index_calendar
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if value.errors.any? %>
  <div id='error_explanation'>
    <ul>
      <% value.errors.full_messages.each do |msg| %>
      <li><%= msg %></li> <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_game.html.erb
<%= form_with(model: game, local: true) do |f| %>
  <div class='conteiner'>
    <div class='row justify-content-center'>
      <div class='col-xl-8 shadow-sm text-main bg-sub-color-gray p-5 mt-sm-5 mb-3'>
        <div class='mb-sm-4'> 
          <h3 class='col-auto'><span class='display-5'>| </span>観戦記録をつける</h3>
        </div>
        <%= render partial: 'shared/error_messages', locals: { value: @game }%>
        <div class='row justify-content-center mb-sm-3 text-center'>
          <div class='col-md-5 shadow-sm p-3 p-sm-5 mb-2 m-sm-4'>
            <div class='game-green'><%= f.label :home_team_id, t('activerecord.attributes.game.home_team'), class: 'col-form-label' %></div>
            <div class='mb-2'><%= f.collection_select(:home_team_id, baseball_teams, :id, :name, {:include_blank => true}, class: 'form-select') %></div>
            <div class=''><%= f.number_field :home_team_score, class: 'form-control', placeholder: '応援チームの得点を入力してください' %></div>
          </div>
          <div class='col-md-5 shadow-sm p-3 p-sm-5 mb-2 m-sm-4'>
            <div class='game-draw'><%= f.label :away_team_id, t('activerecord.attributes.game.away_team'), class: 'col-form-label' %></div>
            <div class='mb-2'><%= f.collection_select(:away_team_id, baseball_teams, :id, :name, {:include_blank => true}, class: 'form-select') %></div>
            <div class=''><%= f.number_field :away_team_score, class: 'form-control', placeholder: '対戦チームの得点を入力してください' %></div>
          </div>
        </div>
        <div class='row justify-content-center'>
          <div class='col-md-5 px-1 px-sm-5 mx-sm-4 mb-2 mb-sm-5 text-center'>
            <div class='game-draw'><%= f.label :date, t('activerecord.attributes.game.date'), class: 'col-form-label' %></div>
            <div class='mb-2'><%= f.date_field :date, class: 'form-control' %></div>
          </div>
          <div class='col-md-5 px-1 px-sm-5 mx-sm-4 mb-2 mb-sm-5 text-center'>
            <div class='game-draw'><%= f.label :baseball_park_id, t('activerecord.attributes.game.baseball_park'), class: 'col-form-label' %></div>
            <div class='mb-2'><%= f.collection_select(:baseball_park_id, baseball_parks, :id, :name, {:include_blank => true}, class: 'form-select') %></div>
          </div>
          <div class='row mb-5'>
            <div class='col-md-2'><%= f.label :memo, t('activerecord.attributes.game.memo'), class: 'col-form-label' %></div>
            <div class='col-md-8'><%= f.text_area :memo, rows: 8, class: 'form-control' %></div>
          </div>
          <div class='d-grid col-8 mx-auto mb-3'>
            <%= f.submit '記録する', class: 'btn-primary-red'%>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_game_calendar.html.erb
<%= month_calendar do |date| %>
  <div><%= date.day %></div>
  <% games_on_date = games.select { |game| game.date.to_date == date } %>
  <% games_on_date.each do |game| %>
    <div class='mb-1 text-center'>
      <% if game.result %>
        <%= link_to result_for_calendar(game.result), game_path(game), class: "btn-#{game.result}" %>
      <% else %>
        <%= link_to '＞', game_path(game), class: 'btn-green' %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_game_list.html.erb
<div class='table-responsive'>
  <table class='table text-nowrap'>
    <thead>
      <tr>
        <th><%= t('activerecord.attributes.game.date') %></th>
        <th><%= t('activerecord.attributes.game.home_team') %></th>
        <th><%= t('activerecord.attributes.game.away_team') %></th>
        <th><%= t('activerecord.attributes.game.baseball_park') %></th>
        <th><%= t('activerecord.attributes.game.result') %></th>
        <th><%= t('activerecord.attributes.game.score') %></th>
      </tr>
    </thead>
    <tbody>
      <% games.each do |game| %>
        <tr class='align-middle'>
          <td><%= l game.date, format: :date %></td>
          <td><%= game.home_team.name %></td>
          <td><%= game.away_team.name %></td>
          <td><%= game.baseball_park.name %></td>
          <td>
            <% if game.result %>
              <%= link_to result_for_calendar(game.result), game_path(game), class: "btn-#{game.result}" %>
            <% else %>
              <%= link_to '＞', game_path(game), class: 'btn-green' %>
            <% end %>
          </td>
          <td><%= game.home_team_score %> - <%= game.away_team_score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_like.html.erb
<% if current_user && current_user.liked_by?(post.id) %>
  <span><%= link_to( post_like_path(post, post.likes.ids), method: :delete, class: 'header-left-btn', remote: true ) do %><i class='bi bi-heart-fill text-main-red fs-4'></i><% end %></span>
<% else %>
  <span><%= link_to( post_likes_path(post), method: :post, class: 'header-left-btn', remote: true ) do %><i class='bi bi-heart text-main-red fs-4'></i><% end %></span>
<% end %>
<span class='me-sm-1 text-main-red'><%= post.likes.count if post.likes.present? %></span>

app/views/shared/_post_show.html.erb
<div class='conteiner'>
  <div class='row justify-content-center'>
    <div class='col-sm-10 shadow-sm text-main bg-sub-color-gray p-5 my-sm-5'>
      <div class='row'>
        <div class='row mb-3'>
          <div class='col-2 col-sm-1 fs-1'>
            <i class="bi bi-person-circle"></i>
          </div>
          <div class='col-10 col-sm-11 text-user-name'>
            <div><%= post.user.name %></div>
            <div><%= l post.updated_at %></div>
          </div>
        </div>
        <div class='mb-3'>
          <div class='text-main'><%= post.title %></div>
        </div>
        <div class='mb-5'>
          <div><%= post.content %></div>
        </div>
        <div class='d-flex justify-content-center mb-5'>
          <%= image_tag post.photo.variant(resize_to_limit: [nil, 400]), class: 'responsive-image' if post.photo.attached? %>
        </div>
        <div class='d-flex flex-column flex-sm-row align-items-center'>
          <div class='me-sm-1'><%= render partial: 'shared/like', locals: { post: post } %></div>
          <div class='me-sm-1'><i class="bi bi-hash"></i><%= post.baseball_team.name %></div>
          <div class='me-sm-1'><i class="bi bi-hash"></i><%= post.baseball_park.name %></div>
          <div class='me-sm-1'><i class="bi bi-hash"></i><%= post.category.name %></div>
        </div>
        <% if defined?(my_posts) %>
          <div class='row mx-auto my-sm-3'>
            <%= link_to "一覧に戻る", my_posts_path, class: 'btn-primary-gray col-sm-4 mb-1' %>
            <%= link_to "変更する", edit_my_post_path(@post), class: 'btn-primary-green col-sm-4 mb-1' %>
            <%= link_to "削除する", my_post_path(@post), method: :delete, class: 'btn-primary-red col-sm-4 mb-1' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_posts_index.html.erb
<% posts.each do |post| %>
  <div class='container'>
    <div class='row mb-3 mb-sm-5 shadow-sm p-4'>
      <div class='col-lg-7'>
        <div class='row mb-sm-3'>
          <div class='col-1 me-sm-3 fs-1'>
            <i class='bi bi-person-circle'></i>
          </div>
          <div class='col-sm-10 text-user-name'>
            <div id='test-post'><%= post.user.name %></div>
            <div><%= l post.updated_at %></div>
          </div>
        </div>
        <div class='mb-sm-3'>
          <div class='fs-3'>
            <% if defined?(my_posts) %>
              <%= link_to post.title, my_post_path(post), class: 'link-text text-main' %>
            <% else %>
              <%= link_to post.title, post_path(post), class: 'link-text text-main' %>
            <% end %>
          </div>
        </div>
      </div>
      <div class='col-lg-5'>
        <%= image_tag post.photo.variant(resize_to_limit: [nil, 400]), class: 'img-fluid' if post.photo.attached? %>
      </div>
      <div class='mt-3 d-flex flex-column flex-md-row align-items-center'>
        <span class='me-md-1' id="like-<%= post.id %>"><%= render partial: 'shared/like', locals: { post: post } %></span>
        <span class='me-md-1'><i class='bi bi-hash'></i><%= post.baseball_team.name %></span>
        <span class='me-md-1'><i class='bi bi-hash'></i><%= post.baseball_park.name %></span>
        <span class='me-md-1'><i class='bi bi-hash'></i><%= post.category.name %></span>
      </div>
    </div>
  </div>
<% end %>
<%= paginate posts, theme: 'bootstrap-5' %>

app/views/shared/_search_form_of_posts.html.erb
<%= search_form_for q do |f| %>
  <div class='container w-sm-50'>
    <div class='row mb-sm-5'>
      <div class='col-sm-3'><%= f.label :title_cont, 'タイトル', class: 'col-form-label' %></div>
      <div class='col-sm-9'><%= f.search_field :title_cont, placeholder: 'キーワードを入力してください', class: 'form-control' %></div>
    </div>
    <div class='row mb-sm-5'>
      <div class='col-sm-3'><%= f.label :baseball_team_id_eq, 'チーム', class: 'col-form-label' %></div>
      <div class='col-sm-9'><%= f.collection_select :baseball_team_id_eq, baseball_teams, :id, :name, {:include_blank => true}, class: 'form-select' %></div>
    </div>
    <div class='row mb-sm-5'>
      <div class='col-sm-3'><%= f.label :baseball_park_id_eq, '球場', class: 'col-form-label' %></div>
      <div class='col-sm-9'><%= f.collection_select :baseball_park_id_eq, baseball_parks, :id, :name, {:include_blank => true}, class: 'form-select' %></div>
    </div>
    <div class='row mb-5'>
      <div class='col-sm-3'><%= f.label :category_id_eq, 'カテゴリー', class: 'col-form-label' %></div>
      <div class='col-sm-9'><%= f.collection_select :category_id_eq, categories, :id, :name, {:include_blank => true}, class: 'form-select' %></div>
    </div>
    <div class='d-grid col-12 mx-auto mb-5'>
      <%= f.submit '検索', class: 'btn-primary-green'%>
    </div>
  </div>
<% end %>

app/views/shared/_user_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render partial: 'shared/error_messages', locals: { value: user }%>
  <div class='row mb-5'>
    <div class='col-sm-4'><%= f.label :name, t('activerecord.attributes.user.name'), class: 'col-form-label' %></div>
    <div class='col-sm-8'><%= f.text_field :name, class: 'form-control' %></div>
  </div>
  <div class='row mb-5'>
    <div class='col-sm-4'><%= f.label :email, t('activerecord.attributes.user.email'), class: 'col-form-label' %></div>
    <div class='col-sm-8'><%= f.text_field :email, class: 'form-control' %></div>
  </div>
  <div class='row mb-5'>
    <div class='col-sm-4'><%= f.label :password, t('activerecord.attributes.user.password'), class: 'col-form-label' %></div>
    <div class='col-sm-8'><%= f.password_field :password, class: 'form-control' %></div>
  </div>
  <div class='row mb-5'>
    <div class='col-sm-4'><%= f.label :password_confirmation, t('activerecord.attributes.user.password_confirmation'), class: 'col-form-label' %></div>
    <div class='col-sm-8'><%= f.password_field :password_confirmation, class: 'form-control' %></div>
  </div>
  <% if defined?(new_user) %>
    <div class='d-grid col-12 mx-auto mb-3'>
      <%= f.submit '新規登録する', class: 'btn-primary-red'%>
    </div>
  <% else %>
    <div class='row mx-auto'>
      <%= link_to '＜　戻る', user_path(@user), class: 'btn-primary-gray col-sm-6' %>
      <%= f.submit '更新', class: 'btn-primary-red col-sm-6'%>
    </div>
  <% end %>
<% end %>