config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#top'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post 'guest_login', to: 'sessions#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :posts, only: [:index, :new, :create, :show] do
    resources :likes, only: [:create, :destroy]
  end
  resources :my_posts, only: [:index, :show, :edit, :update, :destroy]
  resources :games do
    collection do
      get :index_list
      get :index_calendar
    end
  end
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id               :bigint           not null, primary key
#  away_team_score  :integer
#  date             :datetime         not null
#  home_team_score  :integer
#  memo             :text(65535)      not null
#  photo            :string(255)
#  result           :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  away_team_id     :bigint           not null
#  baseball_park_id :bigint           not null
#  home_team_id     :bigint           not null
#  user_id          :bigint           not null
#
# Indexes
#
#  index_games_on_away_team_id      (away_team_id)
#  index_games_on_baseball_park_id  (baseball_park_id)
#  index_games_on_home_team_id      (home_team_id)
#  index_games_on_user_id           (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (away_team_id => baseball_teams.id)
#  fk_rails_...  (baseball_park_id => baseball_parks.id)
#  fk_rails_...  (home_team_id => baseball_teams.id)
#  fk_rails_...  (user_id => users.id)
#
class Game < ApplicationRecord
  before_save :set_result
  before_update :set_result

  belongs_to :home_team, class_name: 'BaseballTeam'
  belongs_to :away_team, class_name: 'BaseballTeam'
  belongs_to :baseball_park
  belongs_to :user

  validates :date, presence: true
  validates :memo, length: { maximum: 1000 }

  def self.win_count
    where(result: 'win').count
  end

  def self.lose_count
    where(result: 'lose').count
  end

  def self.draw_count
    where(result: 'draw').count
  end

  def self.total_result_count
    where(result: ['win', 'lose', 'draw']).count
  end

  def self.win_percentage
    total_games = total_result_count.to_f
    return 0 if total_games.zero?

    (win_count / total_games * 100).round
  end

  def self.current_sequence
    last_results = order(date: :asc).pluck(:result).reject { |result| result == 'scheduled' }.reverse

    sequence_type = nil
    sequence_count = 0

    last_results.each do |result|
      if sequence_type.nil? || sequence_type == result
        sequence_type = result
        sequence_count += 1
      else
        break
      end
    end

    [sequence_type, sequence_count]
  end

  def away_result
    case result
    when 'win'
      'lose'
    when 'lose'
      'win'
    when 'draw'
      'draw'
    else
      'scheduled'
    end
  end

  private

  def set_result
    if home_team_score.nil? || away_team_score.nil?
      return self.result = 'scheduled'
    end

    if home_team_score > away_team_score
      self.result = 'win'
    elsif home_team_score < away_team_score
      self.result = 'lose'
    elsif home_team_score == away_team_score
      self.result = 'draw'
    else
      self.result = 'scheduled'
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :set_games, only: [:index, :index_list, :index_calendar]
  before_action :set_select_values, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_beginning_of_week, only: [:index]

  def new
    @game = Game.new
  end

  def index
  end

  def index_list
  end

  def index_calendar
  end

  def create
    @game = Game.new(game_params.merge(user_id: current_user.id))
    if @game.save
      flash[:success] = '正常に記録しました'
      redirect_to games_path
    else
      flash.now[:danger] = '記録に失敗しました。'
      render new_game_path
    end
  end

  def show
  end

  def edit
  end

  def update
    if @game.update(game_params)
      flash[:success] = '投稿内容を更新しました'
      redirect_to games_path
    else
      flash.now[:danger] = '更新に失敗しました。'
      render 'edit'
    end
  end

  def destroy
    @game.destroy
    flash[:success] = "「#{@game.home_team.name}」 vs 「#{@game.away_team.name}」の観戦記録を削除しました"
    redirect_to games_path
  end

  private

  def game_params
    params.require(:game).permit(:date, :memo, :home_team_id, :away_team_id, :baseball_park_id, :home_team_score,
:away_team_score)
  end

  def set_game
    @game = current_user.games.find(params[:id])
  end

  def set_games
    @games = current_user.games.includes(:user, :baseball_park, :away_team, :home_team).order(:date)
  end

  def set_beginning_of_week
    Date.beginning_of_week = :sunday
  end
end

app/helpers/games_helper.rb
module GamesHelper
  # def mobile_device?
  #   request.user_agent =~ /Mobile|webOS/
  # end

  def result_for_calendar(result)
    case result
    when 'win'
      '◯'
    when 'lose'
      '×'
    when 'draw'
      '△'
    when 'scheduled'
      'ー'
    else
      result
    end
  end
end

app/views/games/edit.html.erb
<%= render partial: 'shared/game', locals: { game: @game, baseball_teams: @baseball_teams, baseball_parks: @baseball_parks } %>

app/views/games/index.html.erb
<div class='conteiner'>
  <div class='row justify-content-center'>
    <div class='col-xl-10 shadow-sm text-main bg-sub-color-gray p-5 mt-sm-5 mb-3'>
      <div class='mb-sm-4'> 
        <h3 class='col-auto'><span class='display-5'>| </span><%= current_user.name %></h3>
      </div>
      <div class='row mb-1 mb-sm-3 justify-content-center'>
        <div class='col-lg-4 text-center shadow-sm win_percentage'>勝率 <span class='number-size'><%= @games.win_percentage %></span> %</div>
        <% sequence_type, sequence_count = @games.current_sequence %>
        <div class='col-lg-4 text-center shadow-sm <%= sequence_type %>-sequence'>
          <% if sequence_type == 'win' %>
            <span class='number-size'><%= sequence_count %></span> 連勝中
          <% elsif sequence_type == 'lose' %>
            <span class='number-size'><%= sequence_count %></span> 連敗中
          <% elsif sequence_type == 'draw' %>
            <span class='number-size'><%= sequence_count %></span> 連分中
          <% else %>
            <%= '連勝・連敗・連続引き分けなし' %>
          <% end %>
        </div>
      </div> 
      <div class='row justify-content-center'>
        <div class='col-lg-2'>
          <div class='game-green text-center'>ALL GAMES</div>
          <div class='green-line text-center'><%= @games.count %></div>
        </div>
        <div class='col-lg-2'>
          <div class='game-win text-center'>WIN</div>
          <div class='win-line text-center'><%= @games.win_count %></div>
        </div>
        <div class='col-lg-2'>
          <div class='game-lose text-center'>LOSE</div>
          <div class='lose-line text-center'><%= @games.lose_count %></div>
        </div>
        <div class='col-lg-2'>
          <div class='game-draw text-center'>DRAW</div>
          <div class='draw-line text-center'><%= @games.draw_count %></div>
        </div>
      </div>
      <div class='row justify-content-center'>
      </div>
    </div>
  </div>
</div>

<div class='conteiner'>
  <div class='row justify-content-center'>
    <div class='col-sm-10 shadow-sm text-main bg-sub-color-gray p-5 my-sm-5'>
      <div class='mb-sm-5'> 
        <h3 class='col-auto'><span class='display-5'>| </span><%= t('activerecord.models.game') %></h3>
        <div class='row justify-content-center'>
          <%= link_to( index_calendar_games_path, remote: true, class: 'col-11 col-sm-3 btn-primary-green mb-2 m-sm-4' ) do %><i class='bi bi-calendar-check-fill'></i> カレンダー表示<% end %>
          <%= link_to( index_list_games_path, remote: true, class: 'col-11 col-sm-3 btn-primary-green mb-2 m-sm-4' ) do %><i class='bi bi-list-check'></i> リスト表示<% end %>
        <div>
      </div>
      <div id='game-view'>
        <%= render partial: 'shared/game_calendar', locals: { games: @games } %>
      </div>
    </div>
  </div>
</div>

app/views/games/index_calendar.js.erb
document.getElementById('game-view').innerHTML = `<%= j(render 'shared/game_calendar', games: @games) %>`;

app/views/games/index_list.js.erb
document.getElementById('game-view').innerHTML = `<%= j(render 'shared/game_list', games: @games) %>`;

app/views/games/new.html.erb
<%= render partial: 'shared/game', locals: { game: @game, baseball_teams: @baseball_teams, baseball_parks: @baseball_parks } %>

app/views/games/show.html.erb
<div class='conteiner'>
  <div class='row justify-content-center'>
    <div class='col-xl-8 shadow-sm text-main bg-sub-color-gray p-5 mt-sm-5 mb-3'>
      <div class='mb-sm-4'> 
        <h3 class='col-auto'><span class='display-5'>| </span><%= t('activerecord.models.game') %></h3>
      </div>
      <div class='row justify-content-center mb-sm-3 text-center'>
        <div class='col-md-5 shadow-sm p-3 p-sm-5 mb-2 m-sm-4 <%= @game.result %>-team'>
          <div class='text-center game-<%= @game.result %>'><%= t('activerecord.attributes.game.home_team') %></div>
          <div class='mb-2'><%= @game.home_team.name %></div>
          <div class='number-size'><%= @game.home_team_score %></div>
        </div>
        <div class='col-md-5 shadow-sm p-3 p-sm-5 mb-2 m-sm-4 <%= @game.away_result %>-team'>
          <div class='game-<%= @game.away_result %>'><%= t('activerecord.attributes.game.away_team') %></div>
          <div class='mb-2'><%= @game.away_team.name %></div>
          <div class='number-size'><%= @game.away_team_score %></div>
        </div>
      </div>
      <div class='row justify-content-center'>
        <div class='col-md-5 px-1 px-sm-5 mx-sm-4 mb-2 mb-sm-5 text-center'>
          <div class='game-draw'><%= t('activerecord.attributes.game.date') %></div>
          <div class='mb-2'><%= l @game.date, format: :date %></div>
        </div>
        <div class='col-md-5 px-1 px-sm-5 mx-sm-4 mb-2 mb-sm-5 text-center'>
          <div class='game-draw'><%= t('activerecord.attributes.game.baseball_park') %></div>
          <div class='mb-2'><%= @game.baseball_park.name %></div>
        </div>
        <div class='row mb-5'>
          <div class='col-md-2'><%= t('activerecord.attributes.game.memo') %></div>
          <div class='col-md-8'><%= @game.memo %></div>
        </div>
        <div class='row justify-content-center my-sm-5'>
          <%= link_to '一覧に戻る', games_path, class: 'btn-primary-gray col-md-3 mb-1 mx-sm-1' %>
          <%= link_to '変更する', edit_game_path(@game), class: 'btn-primary-green col-md-3 mb-1 mx-sm-1' %>
          <%= link_to '削除する', game_path(@game), method: :delete, class: 'btn-primary-red col-md-3 mb-1 mx-sm-1' %>
        </div>
      </div>
    </div>
  </div>
</div>