config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#top'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post 'guest_login', to: 'sessions#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :posts, only: [:index, :new, :create, :show] do
    resources :likes, only: [:create, :destroy]
  end
  resources :my_posts, only: [:index, :show, :edit, :update, :destroy]
  resources :games do
    collection do
      get :index_list
      get :index_calendar
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class='footer py-3 bg-light'>
  <div class='container text-center'>
    <span class='text-muted'>&copy; sekkey_777 2023</span> 
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class='navbar navbar-expand-xl navbar-light bg-sub-color-gray shadow-sm'>
    <div class='container-fluid'>
      <%= link_to( root_path, class: 'header-left-btn' ) do %><i class='bi bi-house-door-fill me-1'></i>ホーム<% end %>
      <button class='navbar-toggler' type='button' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
        <span class='navbar-toggler-icon'></span>
      </button>
      <div class='collapse navbar-collapse' id='navbarSupportedContent'>
        <ul class='navbar-nav me-auto mb-2 mb-lg-0'>
          <li class='nav-item'><%= link_to( posts_path, class: 'header-left-btn' ) do %><i class='bi bi-card-text me-2'></i>投稿<% end %></li>
          <% if logged_in? %>
            <li class='nav-item'><%= link_to( new_post_path, class: 'header-left-btn' ) do %><i class='bi bi-envelope-fill me-2'></i></i>思い出を投稿<% end %></li>
            <li class='nav-item'><%= link_to( my_posts_path, class: 'header-left-btn' ) do %><i class='bi bi-memory me-2'></i>思い出一覧<% end %></li>
            <li class='nav-item'><%= link_to( new_game_path, class: 'header-left-btn' ) do %><i class='bi bi-card-checklist me-2'></i>観戦記録をつける<% end %></li>
            <li class='nav-item'><%= link_to( games_path, class: 'header-left-btn' ) do %><i class='bi bi-list-nested me-2'></i>観戦記録一覧<% end %></li>
            <li class='nav-item'><%= link_to( user_path(current_user), class: 'header-left-btn' ) do %><i class='bi bi-person-fill me-2'></i><%= current_user.name %><% end %></li>
            <li class='nav-item'><%= link_to( logout_path, method: :delete, class: 'header-left-btn' ) do %><i class='bi bi-box-arrow-left me-2'></i>ログアウト<% end %></li>
          <% else %>
            <li class='nav-item'><%= link_to( login_path, class: 'header-left-btn' ) do %><i class='bi bi-box-arrow-in-right me-2'></i>ログイン<% end %></li>
            <li class='nav-item'><%= link_to( login_path(guest_login: true), method: :post, class: 'header-left-btn' ) do %><i class='bi bi-box-arrow-in-right me-2'></i>ゲストログイン<% end %></li>
            <li class='nav-item'><%= link_to( new_user_path, class: 'header-left-btn' ) do %><i class='bi bi-person-plus-fill me-2'></i>新規登録<% end %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baseball Memory</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- BootstrapのCSS -->
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css', integrity: 'sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC', crossorigin: 'anonymous' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class='container w-sm-50 mt-5'>
        <div class='alert alert-<%= message_type %>'><%= message %></div>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <!-- 必要なJavaScriptファイルやライブラリの読み込み -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- BootstrapのJavaScript -->
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js', integrity: 'sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM', crossorigin: 'anonymous' %>
  </body>
</html>